### ISSUE TITLE
No parameterless constructor found exception occurs

### ISSUE THREAD

**Issue by EunjeongChoi414** [max-ieremenko/ServiceModel.Grpc#257]
### Problem 
```csharp
[ServiceContract]
public interface ITestRpc
{
    [OperationContract]
    public Task<TestReturn> TestAsync();
}

[DataContract]
[ProtoContract(SkipConstructor = true)]
public record TestReturn(
    [property: DataMember(Order = 1)] bool IsSuccess);
 ```
 
 whenever I don't put `[ProtoContract(SkipConstructor = true)]` on my return dto, it gives me this exception. 
 ``` text
 Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. ProtoException: No parameterless constructor found
 ```
 
 ### Questions
1. Is this an intended exception? 
2.  Why is there a need for parameterless constructor? 
3.  Is putting the attribute like above the best way to tackle this issue?

**Comment by max-ieremenko** [comment]
I cannot reproduce `ProtoException`:

- use the code from [Examples/ProtobufMarshaller](https://github.com/max-ieremenko/ServiceModel.Grpc/tree/master/Examples/ProtobufMarshaller)
- switch to `<TargetFramework>net8.0</TargetFramework>` in the Contract project (because of record)
- extend existing `IPersonService`
``` c#
    [OperationContract]
    Task<TestReturn> Ping(TestReturn data);
```

It works.
