### ISSUE TITLE
Question, what about performance?

### ISSUE THREAD

**Issue by FireSon** [max-ieremenko/ServiceModel.Grpc#27]
Hi, I was looking for code-first gRPC and found ServiceModel.Grpc. Did you do any performance comparison to other code-first implementations, like protobuf-grpc and MagicOnion? Also since you also implemented a ProtoBufMarshaller... What were the reasons (if any) to not just use protobuf-grpc? 

Very impressed with all the clear examples and documentation! 

Basically I am trying to find out all the reasons to start using ServiceModel.Grpc, do you have some pointers to this?
Thanks!

**Comment by max-ieremenko** [comment]
Hi @FireSon,

by default ServiceModel.Grpc uses DataContractSerializer:
- does not require external assemblies (a part of .net runtime)
- migration from WCF with no effort

DataContractSerializer is not compatible with .proto serialization (gRPC standard), because of this ProtoBufMarshaller is provided as external package.

ServiceModel.Grpc is a tiny layer on top of gRPC C# and grpc-dotnet, helps to adapt code-first to gRPC protocol.
Any performance comparison to other code-first implementations is a comparison of serializer`s performance.
In DataContractMarshaller vs ProtoBufMarshaller for sure .proto serialization wins (ProtoBufMarshaller).

>> why not other code-first implementations?
- support nulls and reference types 
- any call accepts any number of parameters
- external data in streaming calls, see ICalculator.MultiplyBy example on the main page
- exception handling
- source code generation

**Comment by FireSon** [comment]
Hi Max,

Thanks for the info, I missed the ICalculator.MultiplyBy which, if I understand correctly, is a 'callback' routine. Very nice!
The multiple parameters also helps a lot. Is it correct that if you only use value parameters (e.g. string, int etc. ) the serializer is not used? 
Thanks!

**Comment by max-ieremenko** [comment]
The seializer is used always to marshal data between client and server.

**Comment by FireSon** [comment]
Thanks Max!
